export type DelphiIconName =
  | 'abrir_caixa'
  | 'acoes_rapidas'
  | 'ajuda'
  | 'app_logo_cadeado_carrinho'
  | 'arquivo_banco_sqlite'
  | 'atalhos'
  | 'atualizar'
  | 'auditoria_logs'
  | 'backup'
  | 'bloqueio_seguro'
  | 'buscar'
  | 'caixa'
  | 'calendario_data'
  | 'cancelar_venda'
  | 'cartao_credito'
  | 'cartao_debito'
  | 'categorias'
  | 'clientes'
  | 'comprovantes'
  | 'configuracoes'
  | 'crediario'
  | 'dinheiro'
  | 'editar'
  | 'estoque_baixo'
  | 'etiquetas'
  | 'excluir'
  | 'exportar_pdf'
  | 'filtro'
  | 'finalizar_venda'
  | 'fornecedores'
  | 'importar_produtos'
  | 'imprimir'
  | 'loja_ativa'
  | 'manutencao_ajuste'
  | 'novo_item_adicionar'
  | 'observacao'
  | 'offline_local'
  | 'painel_da_loja'
  | 'pedidos'
  | 'pix'
  | 'produtos'
  | 'relatorios'
  | 'remover_menos'
  | 'sistema_local'
  | 'sqlite_ativo'
  | 'transferir_estoque'
  | 'unidades'
  | 'usuario_administrador'
  | 'vendas_pdv'
  | 'whatsapp';

export type DelphiIconSize = 16 | 24 | 32 | 48 | 64;

export function delphiIconSrc(name: DelphiIconName, size: DelphiIconSize): string {
  return `/icons/delphi/png/${size}x${size}/${name}.png`;
}
