-- Smart Loja Fácil PWA + Supabase
-- Migração inicial de referência para uma base limpa web/mobile sincronizada.
-- Ajuste nomes, papéis e políticas antes de usar em produção.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  email text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users(id) on delete restrict,
  phone text not null default '',
  whatsapp text not null default '',
  address text not null default '',
  logo_url text not null default '',
  receipt_message text not null default 'Obrigado pela preferência!',
  low_stock_limit integer not null default 3,
  status text not null default 'active' check (status in ('active', 'blocked', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_members (
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'operator', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (store_id, user_id)
);

create or replace function public.is_store_member(target_store_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.store_members sm
    where sm.store_id = target_store_id
      and sm.user_id = auth.uid()
  );
$$;

create or replace function public.has_store_role(target_store_id uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.store_members sm
    where sm.store_id = target_store_id
      and sm.user_id = auth.uid()
      and sm.role = any(allowed_roles)
  );
$$;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  phone text not null default '',
  whatsapp text not null default '',
  address text not null default '',
  credit_limit numeric(12,2) not null default 0,
  status text not null default 'active' check (status in ('active', 'inactive', 'blocked')),
  notes text not null default '',
  client_request_id text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  name text not null,
  category text not null default '',
  price numeric(12,2) not null default 0,
  promo_price numeric(12,2),
  stock numeric(12,3) not null default 0,
  unit text not null default 'un',
  size text not null default '',
  color text not null default '',
  internal_code text not null default '',
  barcode text not null default '',
  image_url text not null default '',
  status text not null default 'active' check (status in ('active', 'inactive')),
  client_request_id text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  number bigint generated by default as identity,
  client_request_id text not null,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null default 'Balcão',
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('dinheiro', 'pix', 'cartao', 'crediario', 'misto')),
  status text not null default 'finalized' check (status in ('draft', 'finalized', 'canceled')),
  created_by uuid references auth.users(id) on delete set null,
  canceled_at timestamptz,
  cancel_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  sale_id uuid not null references public.sales(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  qty numeric(12,3) not null,
  unit_price numeric(12,2) not null,
  total numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.cash_sessions (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  opened_by uuid references auth.users(id) on delete set null,
  closed_by uuid references auth.users(id) on delete set null,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  opening_amount numeric(12,2) not null default 0,
  closing_amount numeric(12,2),
  status text not null default 'open' check (status in ('open', 'closed')),
  notes text not null default ''
);

create table if not exists public.cash_movements (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  cash_session_id uuid references public.cash_sessions(id) on delete set null,
  client_request_id text not null,
  sale_id uuid references public.sales(id) on delete set null,
  payment_id uuid,
  type text not null check (type in ('entrada', 'saida')),
  method text not null default '',
  amount numeric(12,2) not null,
  reason text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

create table if not exists public.credits (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null,
  sale_id uuid references public.sales(id) on delete set null,
  total numeric(12,2) not null,
  balance numeric(12,2) not null,
  status text not null default 'open' check (status in ('open', 'paid', 'canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.credit_installments (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  credit_id uuid not null references public.credits(id) on delete cascade,
  number integer not null,
  amount numeric(12,2) not null,
  paid_amount numeric(12,2) not null default 0,
  due_date date not null,
  paid_at timestamptz,
  status text not null default 'open' check (status in ('open', 'partial', 'paid', 'canceled')),
  payment_method text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(credit_id, number)
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  client_request_id text not null,
  credit_id uuid references public.credits(id) on delete set null,
  installment_id uuid references public.credit_installments(id) on delete set null,
  amount numeric(12,2) not null,
  method text not null,
  status text not null default 'confirmed' check (status in ('confirmed', 'canceled')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

alter table public.cash_movements
  add constraint cash_movements_payment_fk
  foreign key (payment_id) references public.payments(id) on delete set null;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  number bigint generated by default as identity,
  client_request_id text not null,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null default 'Balcão',
  total numeric(12,2) not null default 0,
  status text not null default 'open' check (status in ('open', 'accepted', 'delivered', 'canceled')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(store_id, client_request_id)
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  qty numeric(12,3) not null,
  unit_price numeric(12,2) not null,
  total numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  sale_id uuid references public.sales(id) on delete set null,
  sale_number bigint,
  receipt_type text not null default '80mm',
  total numeric(12,2) not null default 0,
  content_html text not null default '',
  status text not null default 'generated' check (status in ('generated', 'canceled')),
  created_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  type text not null,
  qty numeric(12,3) not null,
  before_stock numeric(12,3) not null,
  after_stock numeric(12,3) not null,
  reason text not null default '',
  reference_id uuid,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  entity text not null,
  entity_id uuid,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_conflicts (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  entity text not null,
  entity_id uuid,
  client_request_id text,
  local_payload jsonb not null default '{}'::jsonb,
  remote_payload jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'resolved', 'ignored')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Índices principais
create index if not exists idx_customers_store_name on public.customers(store_id, name);
create index if not exists idx_products_store_name on public.products(store_id, name);
create index if not exists idx_products_store_stock on public.products(store_id, stock);
create index if not exists idx_sales_store_created on public.sales(store_id, created_at desc);
create index if not exists idx_cash_movements_store_created on public.cash_movements(store_id, created_at desc);
create index if not exists idx_credits_store_status on public.credits(store_id, status);
create index if not exists idx_orders_store_status on public.orders(store_id, status);
create index if not exists idx_audit_store_created on public.audit_log(store_id, created_at desc);

-- Triggers updated_at
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger stores_set_updated_at before update on public.stores for each row execute function public.set_updated_at();
create trigger customers_set_updated_at before update on public.customers for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger sales_set_updated_at before update on public.sales for each row execute function public.set_updated_at();
create trigger credits_set_updated_at before update on public.credits for each row execute function public.set_updated_at();
create trigger credit_installments_set_updated_at before update on public.credit_installments for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();

-- RLS
alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.store_members enable row level security;
alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.cash_sessions enable row level security;
alter table public.cash_movements enable row level security;
alter table public.credits enable row level security;
alter table public.credit_installments enable row level security;
alter table public.payments enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.receipts enable row level security;
alter table public.stock_movements enable row level security;
alter table public.audit_log enable row level security;
alter table public.sync_conflicts enable row level security;

create policy "profiles_select_self" on public.profiles for select using (auth.uid() is not null and id = auth.uid());
create policy "profiles_update_self" on public.profiles for update using (auth.uid() is not null and id = auth.uid()) with check (auth.uid() is not null and id = auth.uid());
create policy "profiles_insert_self" on public.profiles for insert with check (auth.uid() is not null and id = auth.uid());

create policy "stores_select_member" on public.stores for select using (public.is_store_member(id));
create policy "stores_insert_owner" on public.stores for insert with check (auth.uid() is not null and owner_id = auth.uid());
create policy "stores_update_admin" on public.stores for update using (public.has_store_role(id, array['owner','admin'])) with check (public.has_store_role(id, array['owner','admin']));

create policy "members_select_same_store" on public.store_members for select using (user_id = auth.uid() or public.is_store_member(store_id));
create policy "members_insert_admin" on public.store_members for insert with check (public.has_store_role(store_id, array['owner','admin']) or user_id = auth.uid());
create policy "members_update_owner" on public.store_members for update using (public.has_store_role(store_id, array['owner'])) with check (public.has_store_role(store_id, array['owner']));
create policy "members_delete_owner" on public.store_members for delete using (public.has_store_role(store_id, array['owner']));

-- Políticas comerciais: membros leem; owner/admin/operator escrevem; viewer não escreve.
do $$
declare
  t text;
begin
  foreach t in array array[
    'customers','products','sales','sale_items','cash_sessions','cash_movements','credits','credit_installments',
    'payments','orders','order_items','receipts','stock_movements','audit_log','sync_conflicts'
  ] loop
    execute format('create policy %I on public.%I for select using (public.is_store_member(store_id))', t || '_select_member', t);
    execute format('create policy %I on public.%I for insert with check (public.has_store_role(store_id, array[''owner'',''admin'',''operator'']))', t || '_insert_operator', t);
    execute format('create policy %I on public.%I for update using (public.has_store_role(store_id, array[''owner'',''admin'',''operator''])) with check (public.has_store_role(store_id, array[''owner'',''admin'',''operator'']))', t || '_update_operator', t);
    execute format('create policy %I on public.%I for delete using (public.has_store_role(store_id, array[''owner'',''admin'']))', t || '_delete_admin', t);
  end loop;
end;
$$;
